title: Candidate.SecurityHacker.net
description: Fun and short challenges for Candidate.SecurityHacker.net

remote_theme: pages-themes/architect@v0.2.0

show_downloads: false
repo: false

baseurl: ""
url: "https://candidate.hackerclub.net/"

google_analytics: ""

locale: en_GB
timezone: Europe/London

author: "Antonio Feijao UK"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

