title: Candidate.HackerClub.net
description: Fun and short cyber security challenges

#remote_theme: pages-themes/architect@v0.2.0
remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: pages-themes/midnight@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0

show_downloads: false

baseurl: ""
url: "https://candidate.hackerclub.net"

lang: en-GB
locale: en_GB
timezone: Europe/London

author: "Antonio Feijao UK"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  
